remove unused nsd & fix dns config
Unfortunately I was not able to use nsd because:
- dynamic dns is not availble and I need it for Let's encrypt
- I need to add a return policy for my adblock zone

for the above reason I had to switch to BIND9

diff --git a/dns/scripts/update-named-adblock b/dns/scripts/update-named-adblock
--- a/dns/scripts/update-named-adblock
+++ b/dns/scripts/update-named-adblock
@@ -1,21 +1,64 @@
 #!/usr/bin/env ksh
 set -euo pipefail
 
-set -x #DEBUG
-
-PATH="/bin:/sbin:/usr/local/bin:/usr/bin:/usr/sbin"
+PATH="/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
 COLUMN=120
 
-_tmp=$(mktemp /tmp/temail.XXXXXXX.zone)
-_serial=$(date +'%Y%m%d01')
+_header=$(mktemp /tmp/temail.XXXXXXX.zone)
+_old_block=$(mktemp /tmp/temail.XXXXXXX.zone)
+_block=$(mktemp /tmp/temail.XXXXXXX.zone)
+typeset -i _serial_new=$(date +'%Y%m%d01')
+typeset -i _serial_old=$(date +'%Y%m%d00')
 
-trap "[ -f $_tmp ] && rm -f $_tmp;" ERR EXIT
+_clean=$(cat <<-EOF
+[ -f $_header ] && rm -f $_header;
+[ -f $_block ] && rm -f $_block;
+[ -f $_old_block ] && rm -f $_old_block;
+EOF
+)
+
+_message () {
+   typeset -u mtype # all value are converted to upper case
+   local mpattern="%s: %s\n"
+   local mtab=""
+   mtype=${1:-"Error"}
+   typeset -i numtab=${mtype%%[a-zA-Z]*}
+   shift
+
+   case $numtab in
+       [1-9])
+           for _ in $(seq -s" " ${numtab}); do
+               mtab="\t$mtab"
+           done
+           ;;
+
+   esac
+   mpattern="$mtab$mpattern"
+   mtype="${mtype#[0-9]}"
+
+   if [[ ${mtype} == "ERROR"  ]]; then
+      >&2 printf "$mpattern" $mtype "${@:-\"Something happends...\"}"
+      exit 1
+   else
+       printf "$mpattern" $mtype "${@:-\"Something happends...\"}"
+   fi
+}
+
+trap "$_clean" ERR EXIT
 
 _out="/var/named/zones/adblock.zone"  # zone file
 
-[ -O "$_out" ] || _message "Error" "Cannot alter file: $_out"
+[ -f "$_out" ] || _message "Error" "Cannot alter file: $_out"
 
-sed -e '/^/,/;;--Domain.*/' "$_out" > "$_tmp"
+sed -e '1,/^;;--Domain/ !d' "$_out" > "$_header"
+sed -e '1,/^;;--Domain/ d' "$_out" > "$_old_block"
+
+# Check serial
+_serial_old=$(sed -nE 's/^.[^0-9]+([[:digit:]]+).*;serial/\1/p' "$_header")
+
+if [[ $_serial_new -le ${_serial_old:-0} ]] ; then
+    _serial_new=$(($_serial_old + 1))
+fi
 
 # AdGuard Home
 adguardhome() {
@@ -45,21 +88,30 @@ stevenblack() {
 
 touch "$_out"
 # Grab and format the data
-adguardhome >> "$_tmp"
-stevenblack >> "$_tmp"
+adguardhome >> "$_block"
+stevenblack >> "$_block"
 
 # Clean entries and format entries
 sed -r -e 's/\\//' \
-       -e 's/\.\"/\"/' "$_tmp" |\
+       -e 's/\.\"/\"/' "$_block" |\
 column -t -s '@' |\
-sort -u -o "$_tmp"
+sort -u -o "$_block"
 
 
 # Take action is required
-if $(diff -I'^;;--.*$' -qb "$_out" "$_tmp" >/dev/null 2>&1 ); then
+if $(diff -qb "$_old_block" "$_block" >/dev/null 2>&1 ); then
     _message 'Info' "Add block did not changed... skipping "
 else
     # change serial
-    sed -nEi "/;serial/,/+1/s/(^[[:space:]]+)[0-9]+([[:space:]]+;serial.*$)/\1$_serial\2/" "$_tmp"
-    cat $_tmp > $_out
+    sed -Ei "1,/;refresh/ s/(^[[:space:]]+)[0-9]+([[:space:]]+;serial.*$)/\1$_serial_new\2/" "$_header"
+    cat $_header $_block > $_out
+    chown _bind:_bind $_out
+    named-checkzone adblock $_out
+    if $(rndc -q status >/dev/null 2>&1); then
+      rndc -q reload adblock >/dev/null 2>&1
+    elif $(rcctl ls on | grep -qi isc_named); then
+      rcctl restart isc_named
+      sleep 5
+      rndc -q reload >/dev/null 2>&1
+    fi
 fi
